### ISSUE TITLE
First release?

### ISSUE THREAD

**Issue by EwoutV** [randombyte-developer/advanced-aliases#1]
Hello! I am someone who is very interested in your plugin and can't wait until it will be released. When will you continue developing this? There are many people who are looking for such plugin like this! I can pay you to maybe give you more motivation :p

**Comment by randombyte-developer** [comment]
I am planning to continue development, I didn't delete this repo ;)
But I don't find enough time for development in general. That's why I set priorities, what to work on first. Currently my first priority is finishing an imortant feature in kosp(code shared by some of my plugins) which is crucial for some updating other plugins that have priority(lottery at the top). 
Then this plugin becomes priority number one. I stopped development months ago because there was a problem I couldn't solve. Money won't solve this either ;)
I am interested in releasing this plugin but school and other imortant things take priority first. But thanks for reminding me. :)

**Comment by GershonR** [comment]
Also looking forward to testing and using this! :D

**Comment by randombyte-developer** [comment]
I have found [this](https://forums.spongepowered.org/t/synonym-a-regex-based-command-alias-plugin/16570) which is almost exactly what I wanted to do. Are you all okay with that?

**Comment by EwoutV** [comment]
Hey, sorry for my late reply! That plugin is indeed exactly what I wanted, thanks for showing me!
